r"""Write a squarified treemap of nested proportions as a standalone TikZ file.

Wilke (Nested proportions) recommends a treemap or mosaic for two nested categorical variables: the outer
level gets a hue, the inner level a lightness ladder of that hue, and every rectangle carries its number, since
areas cannot be read precisely. This script lays the rectangles out with the squarify algorithm (Bruls, Huizing,
van Wijk 2000), first the groups, then the items inside each group, so the shapes stay close to squares.

Usage:
    python treemap_from_csv.py data.csv --out treemap.tex [--width 6] [--height 4] [--unit ""]

Input: a header row `group,item,value` and one row per item. Groups are ordered by total (largest first) and
items by value; a label is printed only where it fits (name and value, name alone, or nothing), so small items
are best merged into an "other" row before plotting. Each group carries its name and total in a white strip above
its items (`--header`, 0.3cm), which is not part of the area; the total is dropped when the strip is too
narrow, and a label is never printed wider than its cell.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

GROUP_COLOURS: list[str] = ["setblue", "setpink", "setyellow", "setgreen", "setviolet", "setorange"]
Rect = tuple[float, float, float, float]  # x, y, w, h; y grows downwards (the picture is drawn with y=-1cm)
BS: str = chr(92)  # a backslash, kept out of the string literals


def esc(text: str) -> str:
    return text.replace("&", BS + "&").replace("%", BS + "%").replace("_", BS + "_").replace("#", BS + "#")


def worst_ratio(row: list[float], side: float, scale: float) -> float:
    area: float = sum(row) * scale
    thickness: float = area / side
    ratios: list[float] = []
    for v in row:
        length: float = v * scale / thickness
        ratios.append(max(length / thickness, thickness / length))
    return max(ratios)


def squarify(values: list[float], x: float, y: float, w: float, h: float) -> list[Rect]:
    """Return one rectangle per value (values sorted descending) filling (x, y, w, h)."""
    rects: list[Rect] = []
    rest: list[float] = list(values)
    while rest:
        scale: float = w * h / sum(rest)  # area per unit of value in the remaining region
        side: float = min(w, h)
        row: list[float] = [rest[0]]
        best: float = worst_ratio(row, side, scale)
        for v in rest[1:]:
            candidate: float = worst_ratio(row + [v], side, scale)
            if candidate <= best:
                row.append(v)
                best = candidate
            else:
                break
        thickness: float = sum(row) * scale / side
        offset: float = 0.0
        for v in row:
            length: float = v * scale / thickness
            if w >= h:  # the row runs down the left edge
                rects.append((x, y + offset, thickness, length))
            else:       # the row runs along the top edge
                rects.append((x + offset, y, length, thickness))
            offset += length
        if w >= h:
            x, w = x + thickness, w - thickness
        else:
            y, h = y + thickness, h - thickness
        rest = rest[len(row):]
    return rects


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("csv", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--width", type=float, default=6.0, help="treemap width in cm")
    parser.add_argument("--height", type=float, default=4.0, help="treemap height in cm")
    parser.add_argument("--unit", default="", help="suffix printed after every value, e.g. k")
    parser.add_argument("--gap", type=float, default=1.6, help="white line between groups in pt (items get half)")
    parser.add_argument("--header", type=float, default=0.3, help="height in cm of the strip above each group that holds its name (not counted as area)")
    args = parser.parse_args()

    groups: dict[str, list[tuple[str, float]]] = {}
    with args.csv.open(newline="", encoding="utf-8-sig") as fh:
        for row in csv.DictReader(fh):
            groups.setdefault(row["group"].strip(), []).append((row["item"].strip(), float(row["value"])))
    order: list[str] = sorted(groups, key=lambda g: -sum(v for _, v in groups[g]))
    totals: list[float] = [sum(v for _, v in groups[g]) for g in order]
    group_rects: list[Rect] = squarify(totals, 0.0, 0.0, args.width, args.height)

    lines: list[str] = [
        f"% Generated by treemap_from_csv.py from {args.csv.name}: squarified treemap, hue per group, lightness per item,",
        "% numbers printed where they fit (Wilke, Nested proportions). Regenerate from the CSV rather than editing the numbers.",
        BS + "documentclass[10pt,tikz,border=2pt]{standalone}",
        BS + "usepackage{plotfig}",
        BS + "begin{document}",
        BS + "begin{tikzpicture}[y=-1cm]",
    ]
    for gi, (g, (gx, gy, gw, gh)) in enumerate(zip(order, group_rects)):
        colour: str = GROUP_COLOURS[gi % len(GROUP_COLOURS)]
        items: list[tuple[str, float]] = sorted(groups[g], key=lambda t: -t[1])
        hdr: float = args.header if gh > 2 * args.header else 0.0
        item_rects: list[Rect] = squarify([v for _, v in items], gx, gy + hdr, gw, gh - hdr)
        for ii, ((name, value), (x, y, w, h)) in enumerate(zip(items, item_rects)):
            shade: int = 100 - round(45 * ii / max(1, len(items) - 1))  # 100 down to 55 percent of the hue
            lines.append(BS + f"fill[{colour}!{shade}!white] ({x:.3f},{y:.3f}) rectangle ({x + w:.3f},{y + h:.3f});")
            label: str = ""
            name_w: float = 0.11 * len(name) + 0.12  # cm at 6.5pt; the value line is never wider than the name
            if w > name_w and h > 0.55:
                label = esc(name) + BS + BS + "{" + BS + "ttfamily " + f"{value:g}{esc(args.unit)}" + "}"
            elif w > name_w and h > 0.3:
                label = esc(name)
            if label:
                lines.append(BS + "node[font=" + BS + "fontsize{6.5}{7.5}" + BS + "selectfont, text=ink, align=center, inner sep=1pt]"
                             f" at ({x + w / 2:.3f},{y + h / 2:.3f}) {{{label}}};")
        # white separators: thin between items, thicker around the group
        for x, y, w, h in item_rects:
            lines.append(BS + f"draw[white, line width={args.gap / 2:.2f}pt] ({x:.3f},{y:.3f}) rectangle ({x + w:.3f},{y + h:.3f});")
        lines.append(BS + f"draw[white, line width={args.gap:.2f}pt] ({gx:.3f},{gy:.3f}) rectangle ({gx + gw:.3f},{gy + gh:.3f});")
        total_txt: str = f"{totals[gi]:g}{esc(args.unit)}"
        head: str = esc(g) + " {" + BS + "mdseries" + BS + "ttfamily " + total_txt + "}"
        if 0.13 * (len(g) + len(total_txt) + 1) + 0.16 > gw:  # bold 7pt: about 0.13cm per character
            head = esc(g) if 0.13 * len(g) + 0.16 <= gw else ""
        if hdr > 0 and head:
            lines.append(BS + "node[anchor=west, font=" + BS + "fontsize{7}{8}" + BS + "bfseries" + BS + "selectfont,"
                         f" text={colour}!45!black, inner sep=0pt] at ({gx + 0.08:.3f},{gy + hdr / 2:.3f}) {{{head}}};")
    lines += [BS + "end{tikzpicture}", BS + "end{document}", ""]
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[treemap] wrote {args.out}: {len(order)} groups, {sum(len(v) for v in groups.values())} items")


if __name__ == "__main__":
    main()
